package Cursos;

import Materia.Asignatura;
import frontEs.dashboard;
import frontMon.dashboardMon;
import java.awt.Color;

public class panelCurso extends javax.swing.JPanel {

    private Asignatura asignaturaActual;

    public panelCurso() {
        initComponents();

    }

    public panelCurso(Asignatura asig) {
        initComponents();
        this.asignaturaActual = asig;
        cargarDatosAsignatura();
    }
        //Metodo para cargar las asignaturas//

    private void cargarDatosAsignatura() {
        if (asignaturaActual != null) {
            videoName.setText(asignaturaActual.getNombre());

            descripTxt.setText(asignaturaActual.getDescripcion());

        } else {
            videoName.setText("Error: Asignatura no cargada");
            descripTxt.setText("Verifique el objeto Asignatura pasado al constructor.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        videoName = new javax.swing.JLabel();
        descripTxt = new javax.swing.JLabel();
        imgAsig = new javax.swing.JPanel();
        accAsigBtn = new javax.swing.JPanel();
        accAsigTxt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        videoName.setFont(new java.awt.Font("Poppins SemiBold", 0, 26)); // NOI18N
        videoName.setForeground(new java.awt.Color(0, 0, 0));
        videoName.setText("Asignatura");
        jPanel1.add(videoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 370, 30));

        descripTxt.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        descripTxt.setForeground(new java.awt.Color(0, 0, 0));
        descripTxt.setText("Descripción...");
        descripTxt.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(descripTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 170, 140));

        imgAsig.setBackground(new java.awt.Color(64, 174, 178));

        javax.swing.GroupLayout imgAsigLayout = new javax.swing.GroupLayout(imgAsig);
        imgAsig.setLayout(imgAsigLayout);
        imgAsigLayout.setHorizontalGroup(
            imgAsigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );
        imgAsigLayout.setVerticalGroup(
            imgAsigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
        );

        jPanel1.add(imgAsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 17, -1, -1));

        accAsigBtn.setBackground(new java.awt.Color(247, 247, 247));
        accAsigBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 174, 178), 2));

        accAsigTxt.setFont(new java.awt.Font("Questrial", 0, 14)); // NOI18N
        accAsigTxt.setForeground(new java.awt.Color(64, 174, 178));
        accAsigTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accAsigTxt.setText("Acceder");
        accAsigTxt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                accAsigTxtMouseMoved(evt);
            }
        });
        accAsigTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accAsigTxtMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accAsigTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout accAsigBtnLayout = new javax.swing.GroupLayout(accAsigBtn);
        accAsigBtn.setLayout(accAsigBtnLayout);
        accAsigBtnLayout.setHorizontalGroup(
            accAsigBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
            .addGroup(accAsigBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(accAsigTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
        );
        accAsigBtnLayout.setVerticalGroup(
            accAsigBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
            .addGroup(accAsigBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(accAsigTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
        );

        jPanel1.add(accAsigBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 120, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 215));
    }// </editor-fold>//GEN-END:initComponents

    private void accAsigTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accAsigTxtMouseClicked

        back.Usuario usuario = back.Session.getUsuario();

        if (usuario == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "❌ Error: No hay sesión de usuario activa. Vuelva a iniciar sesión.",
                    "Error de Sesión", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String rol = usuario.getRol();
        System.out.println("Rol del usuario: " + rol);

        if ("Estudiante".equalsIgnoreCase(rol)) {
            dashboard nuevaventana = new dashboard();
            nuevaventana.setVisible(true);

        } else if ("Monitor/tutor".equalsIgnoreCase(rol)) {
            dashboardMon nuevaventana = new dashboardMon();
            nuevaventana.setVisible(true);

        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "⚠️ Rol desconocido (" + rol + "). Contacte al administrador.");
            return;
        }

        //Cierre de la ventana actual
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }// Cierra el JFrame que contiene este panel

    }//GEN-LAST:event_accAsigTxtMouseClicked

    private void accAsigTxtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accAsigTxtMouseMoved
        accAsigBtn.setBackground(new Color(64, 174, 178));
        accAsigTxt.setForeground(new Color(247, 247, 247));
    }//GEN-LAST:event_accAsigTxtMouseMoved

    private void accAsigTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accAsigTxtMouseExited
        accAsigBtn.setBackground(new Color(247, 247, 247));
        accAsigTxt.setForeground(new Color(64, 174, 178));
    }//GEN-LAST:event_accAsigTxtMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accAsigBtn;
    private javax.swing.JLabel accAsigTxt;
    private javax.swing.JLabel descripTxt;
    private javax.swing.JPanel imgAsig;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel videoName;
    // End of variables declaration//GEN-END:variables
}
