package Cursos;



public class panelNotif extends javax.swing.JPanel {

  
    public panelNotif() {
        initComponents();
    }

              //Metodo para el horario
    
    public void setHorarioData(String nombreAsignatura, String nombreDocente, String salon, String dia, String horaInicio, String horaFin) {
        
        asigNotif.setText(nombreAsignatura);
        docenteNotif.setText(nombreDocente);
        
    
        salonNotif.setText("Salón: " + salon);
        diaNotif.setText("Día: " + dia);
        
        
        hinicioNotif.setText(horaInicio);
        hsalidaNotif.setText(horaFin);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardNotif = new javax.swing.JPanel();
        hsalidaNotif = new javax.swing.JLabel();
        div = new javax.swing.JLabel();
        asigNotif = new javax.swing.JLabel();
        salonNotif = new javax.swing.JLabel();
        docenteNotif = new javax.swing.JLabel();
        diaNotif = new javax.swing.JLabel();
        hinicioNotif = new javax.swing.JLabel();
        grayPanel = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardNotif.setBackground(new java.awt.Color(247, 247, 247));
        cardNotif.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hsalidaNotif.setFont(new java.awt.Font("Questrial", 0, 14)); // NOI18N
        hsalidaNotif.setForeground(new java.awt.Color(0, 0, 0));
        hsalidaNotif.setText("Salida");
        cardNotif.add(hsalidaNotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 60, -1));

        div.setFont(new java.awt.Font("Questrial", 0, 14)); // NOI18N
        div.setForeground(new java.awt.Color(0, 0, 0));
        div.setText("|");
        cardNotif.add(div, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 10, -1));

        asigNotif.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        asigNotif.setForeground(new java.awt.Color(0, 0, 0));
        asigNotif.setText("Asignatura");
        cardNotif.add(asigNotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 20));

        salonNotif.setFont(new java.awt.Font("Questrial", 0, 14)); // NOI18N
        salonNotif.setForeground(new java.awt.Color(0, 0, 0));
        salonNotif.setText("Salon ");
        cardNotif.add(salonNotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 200, -1));

        docenteNotif.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        docenteNotif.setForeground(new java.awt.Color(0, 0, 0));
        docenteNotif.setText("Docente");
        cardNotif.add(docenteNotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 20));

        diaNotif.setFont(new java.awt.Font("Questrial", 0, 14)); // NOI18N
        diaNotif.setForeground(new java.awt.Color(0, 0, 0));
        diaNotif.setText("Día");
        cardNotif.add(diaNotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, -1));

        hinicioNotif.setFont(new java.awt.Font("Questrial", 0, 14)); // NOI18N
        hinicioNotif.setForeground(new java.awt.Color(0, 0, 0));
        hinicioNotif.setText("Inicio");
        cardNotif.add(hinicioNotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 60, -1));

        grayPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout grayPanelLayout = new javax.swing.GroupLayout(grayPanel);
        grayPanel.setLayout(grayPanelLayout);
        grayPanelLayout.setHorizontalGroup(
            grayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        grayPanelLayout.setVerticalGroup(
            grayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        cardNotif.add(grayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 54));

        add(cardNotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 160));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asigNotif;
    private javax.swing.JPanel cardNotif;
    private javax.swing.JLabel diaNotif;
    private javax.swing.JLabel div;
    private javax.swing.JLabel docenteNotif;
    private javax.swing.JPanel grayPanel;
    private javax.swing.JLabel hinicioNotif;
    private javax.swing.JLabel hsalidaNotif;
    private javax.swing.JLabel salonNotif;
    // End of variables declaration//GEN-END:variables
}
