

package Cursos;


import Materia.Asignatura; // Ejemplo: Si está en el paquete Materia
import Materia.Asignatura; 
import javax.swing.SwingUtilities;
import java.awt.Component;
// import Materia.ClaseDeAsignatura; // Usa el nombre correcto de tu clase de modelo

/**
 *
 * @author Mi PC HOLIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII helllooooooooooooooo
 */
public class panelCurso extends javax.swing.JPanel {

    // Variable para almacenar el objeto Asignatura si es necesario para acciones posteriores
    private Asignatura asignaturaActual; 

    /**
     * Constructor por defecto (mantener si es necesario para el diseñador de NetBeans).
     * Nota: En la aplicación, usaremos el constructor con parámetros.
     */
    public panelCurso() {
        initComponents();
        // Si usas este constructor, las etiquetas tendrán los valores por defecto
    }

    // -------------------------------------------------------------
    // 🔥 NUEVO CONSTRUCTOR: Recibe la Asignatura y actualiza la UI
    // -------------------------------------------------------------
    /**
     * Crea un nuevo panelCurso y lo inicializa con los datos de la asignatura.
     * @param asig El objeto Asignatura que contiene el nombre y descripción.
     */
    public panelCurso(Asignatura asig) {
        initComponents();
        this.asignaturaActual = asig;
        cargarDatosAsignatura(); 
    }
    
    // -------------------------------------------------------------
    // 🔥 MÉTODO: Carga los datos de la Asignatura en los JLabel
    // -------------------------------------------------------------
    private void cargarDatosAsignatura() {
        if (asignaturaActual != null) {
            // Asumo que tu clase Asignatura tiene métodos getNombre() y getDescripcion()
            
            // Asigna el nombre de la asignatura al JLabel videoName
            videoName.setText(asignaturaActual.getNombre()); 
            
            // Asigna la descripción de la asignatura al JLabel descripTxt
            descripTxt.setText(asignaturaActual.getDescripcion());
            
            // Opcional: Podrías querer configurar la acción del botón "Acceder" aquí
            // accAsigBtn.addMouseListener(new java.awt.event.MouseAdapter() { ... });
            
        } else {
            videoName.setText("Error: Asignatura no cargada");
            descripTxt.setText("Verifique el objeto Asignatura pasado al constructor.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        videoName = new javax.swing.JLabel();
        descripTxt = new javax.swing.JLabel();
        imgAsig = new javax.swing.JPanel();
        accAsigBtn = new javax.swing.JPanel();
        accAsigTxt = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        videoName.setFont(new java.awt.Font("Poppins SemiBold", 0, 26)); // NOI18N
        videoName.setForeground(new java.awt.Color(0, 0, 0));
        videoName.setText("Asignatura");
        jPanel1.add(videoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 370, 30));

        descripTxt.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        descripTxt.setForeground(new java.awt.Color(0, 0, 0));
        descripTxt.setText("Descripción...");
        descripTxt.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(descripTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 240, 140));

        imgAsig.setBackground(new java.awt.Color(64, 174, 178));

        javax.swing.GroupLayout imgAsigLayout = new javax.swing.GroupLayout(imgAsig);
        imgAsig.setLayout(imgAsigLayout);
        imgAsigLayout.setHorizontalGroup(
            imgAsigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );
        imgAsigLayout.setVerticalGroup(
            imgAsigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
        );

        jPanel1.add(imgAsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 17, -1, -1));

        accAsigBtn.setBackground(new java.awt.Color(247, 247, 247));
        accAsigBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 174, 178), 2));
        accAsigBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accAsigBtnMouseClicked(evt);
            }
        });

        accAsigTxt.setFont(new java.awt.Font("Questrial", 0, 14)); // NOI18N
        accAsigTxt.setForeground(new java.awt.Color(64, 174, 178));
        accAsigTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accAsigTxt.setText("Acceder");

        javax.swing.GroupLayout accAsigBtnLayout = new javax.swing.GroupLayout(accAsigBtn);
        accAsigBtn.setLayout(accAsigBtnLayout);
        accAsigBtnLayout.setHorizontalGroup(
            accAsigBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accAsigTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );
        accAsigBtnLayout.setVerticalGroup(
            accAsigBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accAsigTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel1.add(accAsigBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 170, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accAsigBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accAsigBtnMouseClicked
        //:
    }//GEN-LAST:event_accAsigBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accAsigBtn;
    private javax.swing.JLabel accAsigTxt;
    private javax.swing.JLabel descripTxt;
    private javax.swing.JPanel imgAsig;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel videoName;
    // End of variables declaration//GEN-END:variables
}
