package Dashboard;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author Mi PC
 */
public class actDash extends javax.swing.JPanel {

    /**
     * Creates new form act
     */
    public actDash() {
        initComponents();
    }
    private String actividadURL;

    // ==================== GETTER CLAVE CORREGIDO ====================
    public javax.swing.JPanel getDownloadBtn1() {  
        // Esta variable (downloadBtn) se inicializa en initComponents()
        return downloadBtn1;
    }

    public javax.swing.JLabel getActividadName() {
        return actName;
    }

    public javax.swing.JLabel getDocenteName() {
        return docenteName;
    }

    public javax.swing.JLabel getAsigName() {
        return asigTxt;
    }

    // ==================== SET DATA ====================
    public void setActividadData(String titulo, String docente, String asignatura, String actividadURL) {
        this.actName.setText(titulo);
        this.docenteName.setText(docente);
        this.asigTxt.setText(asignatura);
        this.actividadURL = actividadURL;
    }

    public String getActividadURL() {
        return actividadURL;
    }
     private void abrirActividad() {
        if (actividadURL == null || actividadURL.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Error: No se encontró la ruta o URL de la actividad.", 
                "Error de Apertura", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            File activityFile = new File(actividadURL);
            
            // 1. Intentar abrir como archivo local (si existe)
            if (Desktop.isDesktopSupported() && activityFile.exists()) {
                Desktop.getDesktop().open(activityFile);
                JOptionPane.showMessageDialog(this, "Archivo de actividad abierto");
            } 
            // 2. Intentar abrir como URL web (si comienza con http)
            else if (actividadURL.toLowerCase().startsWith("http")) {
                Desktop.getDesktop().browse(new URI(actividadURL));
                 JOptionPane.showMessageDialog(this, "URL de actividad abierta");
            }
            // 3. El archivo no existe
            else if (!activityFile.exists()) {
                 JOptionPane.showMessageDialog(this, 
                    "Error: Archivo de actividad no encontrado en la ruta:\n" + actividadURL, 
                    "Archivo No Encontrado", JOptionPane.ERROR_MESSAGE);
            } else {
                 JOptionPane.showMessageDialog(this, 
                    "Error: La apertura externa no está soportada en este sistema.", 
                    "Error de Sistema", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) { 
            JOptionPane.showMessageDialog(this, 
                "Ocurrió un error al intentar abrir la actividad. Detalle: " + ex.getMessage(), 
                "Error I/O/URL", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        downloadBtn1 = new javax.swing.JPanel();
        downloadTxt1 = new javax.swing.JLabel();
        actName = new javax.swing.JLabel();
        asigTxt = new javax.swing.JLabel();
        docenteName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        downloadBtn1.setBackground(new java.awt.Color(64, 174, 178));

        downloadTxt1.setFont(new java.awt.Font("Questrial", 0, 14)); // NOI18N
        downloadTxt1.setForeground(new java.awt.Color(255, 255, 255));
        downloadTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        downloadTxt1.setText("Descargar");
        downloadTxt1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                downloadTxt1MouseMoved(evt);
            }
        });
        downloadTxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downloadTxt1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                downloadTxt1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout downloadBtn1Layout = new javax.swing.GroupLayout(downloadBtn1);
        downloadBtn1.setLayout(downloadBtn1Layout);
        downloadBtn1Layout.setHorizontalGroup(
            downloadBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(downloadTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        downloadBtn1Layout.setVerticalGroup(
            downloadBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(downloadTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        add(downloadBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(836, 4, 150, 22));

        actName.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        actName.setForeground(new java.awt.Color(0, 0, 0));
        actName.setText("Actividad.pdf");
        add(actName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 260, 30));

        asigTxt.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        asigTxt.setForeground(new java.awt.Color(0, 0, 0));
        asigTxt.setText("Asignatura");
        add(asigTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 210, 30));

        docenteName.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        docenteName.setForeground(new java.awt.Color(0, 0, 0));
        docenteName.setText("Nombre");
        add(docenteName, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void downloadTxt1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downloadTxt1MouseMoved
        downloadBtn1.setBackground(new Color(38, 114, 116));
    }//GEN-LAST:event_downloadTxt1MouseMoved

    private void downloadTxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downloadTxt1MouseClicked
       abrirActividad();
    }//GEN-LAST:event_downloadTxt1MouseClicked

    private void downloadTxt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downloadTxt1MouseExited
        downloadBtn1.setBackground(new Color(4, 174, 178));
    }//GEN-LAST:event_downloadTxt1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actName;
    private javax.swing.JLabel asigTxt;
    private javax.swing.JLabel docenteName;
    private javax.swing.JPanel downloadBtn1;
    private javax.swing.JLabel downloadTxt1;
    // End of variables declaration//GEN-END:variables
}
