
package Dashboard;

import javax.swing.JPanel;

/**
 *
 * @author Mi PC
 */
public class actDash extends javax.swing.JPanel {

    /**
     * Creates new form act
     */
    public actDash() {
        initComponents();
    }
    private String actividadURL;

    // ==================== GETTERS CORREGIDOS ====================
    public javax.swing.JPanel getDownloadBtn() {  // ← MANTÉN ESTE
        return downloadBtn;
    }

    public javax.swing.JLabel getActividadName() {
        return actName;
    }

    public javax.swing.JLabel getDocenteName() {
        return docenteName;
    }

    public javax.swing.JLabel getAsigName() {
        return asigTxt;
    }

    // ==================== SET DATA ====================
    public void setActividadData(String titulo, String docente, String asignatura, String actividadURL) {
        this.actName.setText(titulo);
        this.docenteName.setText(docente);
        this.asigTxt.setText(asignatura);
        this.actividadURL = actividadURL;
    }

    public String getActividadURL() {
        return actividadURL;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        downloadBtn1 = new javax.swing.JPanel();
        downloadTxt1 = new javax.swing.JLabel();
        actName = new javax.swing.JLabel();
        asigTxt = new javax.swing.JLabel();
        docenteName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        downloadBtn1.setBackground(new java.awt.Color(64, 174, 178));

        downloadTxt1.setFont(new java.awt.Font("Questrial", 0, 14)); // NOI18N
        downloadTxt1.setForeground(new java.awt.Color(255, 255, 255));
        downloadTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        downloadTxt1.setText("Descargar");

        javax.swing.GroupLayout downloadBtn1Layout = new javax.swing.GroupLayout(downloadBtn1);
        downloadBtn1.setLayout(downloadBtn1Layout);
        downloadBtn1Layout.setHorizontalGroup(
            downloadBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(downloadTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        downloadBtn1Layout.setVerticalGroup(
            downloadBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(downloadTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        actName.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        actName.setForeground(new java.awt.Color(0, 0, 0));
        actName.setText("Actividad.pdf");

        asigTxt.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        asigTxt.setForeground(new java.awt.Color(0, 0, 0));
        asigTxt.setText("Asignatura");

        docenteName.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        docenteName.setForeground(new java.awt.Color(0, 0, 0));
        docenteName.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(actName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(asigTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(docenteName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(downloadBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(asigTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(docenteName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(downloadBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actName;
    private javax.swing.JLabel asigTxt;
    private javax.swing.JLabel docenteName;
    private javax.swing.JPanel downloadBtn;
    private javax.swing.JPanel downloadBtn1;
    private javax.swing.JLabel downloadTxt;
    private javax.swing.JLabel downloadTxt1;
    // End of variables declaration//GEN-END:variables
}
