/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dashboard;

/**
 *
 * @author Mi PC
 */
public class actDash extends javax.swing.JFrame {

    /**
     * Creates new form actDash
     */
    public actDash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        activity = new javax.swing.JPanel();
        downloadBtn = new javax.swing.JPanel();
        downloadTxt = new javax.swing.JLabel();
        actName = new javax.swing.JLabel();
        asigTxt = new javax.swing.JLabel();
        docenteName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        activity.setBackground(new java.awt.Color(255, 255, 255));
        activity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        activity.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        downloadBtn.setBackground(new java.awt.Color(64, 174, 178));

        downloadTxt.setFont(new java.awt.Font("Questrial", 0, 14)); // NOI18N
        downloadTxt.setForeground(new java.awt.Color(255, 255, 255));
        downloadTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        downloadTxt.setText("Descargar");

        javax.swing.GroupLayout downloadBtnLayout = new javax.swing.GroupLayout(downloadBtn);
        downloadBtn.setLayout(downloadBtnLayout);
        downloadBtnLayout.setHorizontalGroup(
            downloadBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(downloadTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        downloadBtnLayout.setVerticalGroup(
            downloadBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(downloadTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        activity.add(downloadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(856, 4, 130, 22));

        actName.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        actName.setForeground(new java.awt.Color(0, 0, 0));
        actName.setText("Actividad.pdf");
        activity.add(actName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 260, 30));

        asigTxt.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        asigTxt.setForeground(new java.awt.Color(0, 0, 0));
        asigTxt.setText("Asignatura");
        activity.add(asigTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 210, 30));

        docenteName.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        docenteName.setForeground(new java.awt.Color(0, 0, 0));
        docenteName.setText("Nombre");
        activity.add(docenteName, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 180, 30));

        getContentPane().add(activity, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the comactivityne arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new actDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actName;
    private javax.swing.JPanel activity;
    private javax.swing.JLabel asigTxt;
    private javax.swing.JLabel docenteName;
    private javax.swing.JPanel downloadBtn;
    private javax.swing.JLabel downloadTxt;
    // End of variables declaration//GEN-END:variables
}
