/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontMon;

import back.Session;
import back.Usuario;
import front.login;
import frontMon.profileMon;
import frontMon.cursosDashMon;
import frontMon.dashboardMon;
import frontMon.docente;
import javax.swing.UIManager;
import back.Actualizable;

/**
 *
 * @author Mi PC
 */
public class actDashMon extends javax.swing.JFrame implements Actualizable {

    /**
     * Creates new form login
     */
    public actDashMon() {
        initComponents();
        cargarUsuario(); // <-- IMPORTANTE
    }

    private void cargarUsuario() {
        Usuario u = Session.getUsuario();

        if (u != null) {
            userName.setText(u.getNombre() + " " + u.getApellido());
        } else {
            userName.setText("Usuario");
        }

    }

    public void actualizarNombreEnUI() {
        // Asegúrate de usar la misma lógica que usabas para cargar el nombre
        Usuario u = back.Session.getUsuario();
        // O Usuario u = back.Manager.getUsuarioActual(); (depende de tu clase de sesión)

        if (u != null) {
            // 'userName' debe ser el nombre de tu JLabel en la esquina superior
            userName.setText(u.getNombre() + " " + u.getApellido());
        } else {
            userName.setText("Usuario");
        }
        this.revalidate();
        this.repaint();
        System.out.println("✅ Dashboard: Nombre de usuario recargado.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        docBtn = new javax.swing.JPanel();
        docTxt = new javax.swing.JLabel();
        docIcon = new javax.swing.JLabel();
        sectionName = new javax.swing.JPanel();
        completeTxt = new javax.swing.JLabel();
        activesTxt = new javax.swing.JLabel();
        allTxt = new javax.swing.JLabel();
        actsTitle = new javax.swing.JLabel();
        filterIcon = new javax.swing.JLabel();
        listIcon = new javax.swing.JLabel();
        allBtn = new javax.swing.JLabel();
        activesBtn = new javax.swing.JLabel();
        completeBtn = new javax.swing.JLabel();
        menuBar = new javax.swing.JPanel();
        appName = new javax.swing.JLabel();
        dashBtn = new javax.swing.JPanel();
        dashTxt = new javax.swing.JLabel();
        dashIcon = new javax.swing.JLabel();
        coursesBtn = new javax.swing.JPanel();
        coursesTxt = new javax.swing.JLabel();
        coursesIcon = new javax.swing.JLabel();
        actsBtn = new javax.swing.JPanel();
        actsTxt = new javax.swing.JLabel();
        actsIcon = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JPanel();
        logoutTxt = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        searchIcon = new javax.swing.JButton();
        searchBar = new javax.swing.JTextField();
        profilePic = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        configArrow = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mainCont = new javax.swing.JPanel();
        tabbed = new javax.swing.JTabbedPane();
        activesTab = new javax.swing.JTabbedPane();
        completeTab = new javax.swing.JTabbedPane();
        allTab = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        docBtn.setBackground(new java.awt.Color(255, 255, 255));
        docBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docBtnMouseClicked(evt);
            }
        });
        docBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        docTxt.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        docTxt.setForeground(new java.awt.Color(0, 0, 0));
        docTxt.setText("Docente");
        docBtn.add(docTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 13, -1, -1));

        docIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/caseBlack.png"))); // NOI18N
        docBtn.add(docIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        getContentPane().add(docBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 260, 40));

        sectionName.setBackground(new java.awt.Color(153, 153, 153));
        sectionName.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        completeTxt.setFont(new java.awt.Font("Open Sans", 0, 9)); // NOI18N
        completeTxt.setForeground(new java.awt.Color(0, 0, 0));
        completeTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completeTxt.setText("Terminadas");
        sectionName.add(completeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, 20));

        activesTxt.setFont(new java.awt.Font("Open Sans", 0, 9)); // NOI18N
        activesTxt.setForeground(new java.awt.Color(0, 0, 0));
        activesTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activesTxt.setText("Activas");
        sectionName.add(activesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 40, 20));

        allTxt.setFont(new java.awt.Font("Open Sans", 1, 9)); // NOI18N
        allTxt.setForeground(new java.awt.Color(255, 255, 255));
        allTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        allTxt.setText("Todas");
        sectionName.add(allTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 50, 40, 20));

        actsTitle.setFont(new java.awt.Font("Questrial", 0, 35)); // NOI18N
        actsTitle.setForeground(new java.awt.Color(0, 0, 0));
        actsTitle.setText("Mis actividades");
        sectionName.add(actsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        filterIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/filter.png"))); // NOI18N
        sectionName.add(filterIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 40, 40));

        listIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N
        sectionName.add(listIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 40, 40));

        allBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/filterGreen.png"))); // NOI18N
        sectionName.add(allBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        activesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/filterGray.png"))); // NOI18N
        sectionName.add(activesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, 20));

        completeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/filterGraybigger.png"))); // NOI18N
        sectionName.add(completeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 89, 20));

        getContentPane().add(sectionName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 1010, 80));

        menuBar.setBackground(new java.awt.Color(255, 255, 255));
        menuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        appName.setFont(new java.awt.Font("Questrial", 0, 30)); // NOI18N
        appName.setForeground(new java.awt.Color(0, 0, 0));
        appName.setText("Skillbridge");
        menuBar.add(appName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        dashBtn.setBackground(new java.awt.Color(255, 255, 255));
        dashBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashBtnMouseClicked(evt);
            }
        });
        dashBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashTxt.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        dashTxt.setForeground(new java.awt.Color(0, 0, 0));
        dashTxt.setText("Dashboard");
        dashBtn.add(dashTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 13, 80, -1));

        dashIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/houseBicon.png"))); // NOI18N
        dashBtn.add(dashIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        menuBar.add(dashBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, 40));

        coursesBtn.setBackground(new java.awt.Color(255, 255, 255));
        coursesBtn.setForeground(new java.awt.Color(0, 0, 0));
        coursesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coursesBtnMouseClicked(evt);
            }
        });
        coursesBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coursesTxt.setBackground(new java.awt.Color(255, 255, 255));
        coursesTxt.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        coursesTxt.setForeground(new java.awt.Color(0, 0, 0));
        coursesTxt.setText("Cursos");
        coursesBtn.add(coursesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 13, 50, -1));

        coursesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hatBicon.png"))); // NOI18N
        coursesBtn.add(coursesIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        menuBar.add(coursesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 260, 40));

        actsBtn.setBackground(new java.awt.Color(255, 255, 255));
        actsBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        actsTxt.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        actsTxt.setForeground(new java.awt.Color(64, 174, 178));
        actsTxt.setText("Actividades");
        actsBtn.add(actsTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 13, -1, -1));

        actsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/appleGicon.png"))); // NOI18N
        actsBtn.add(actsIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        menuBar.add(actsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 260, 40));

        logoutBtn.setBackground(new java.awt.Color(255, 255, 255));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });
        logoutBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutTxt.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        logoutTxt.setForeground(new java.awt.Color(0, 0, 0));
        logoutTxt.setText("Log out");
        logoutBtn.add(logoutTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 13, -1, -1));

        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoutIcon.png"))); // NOI18N
        logoutBtn.add(logoutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        menuBar.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 260, 40));

        getContentPane().add(menuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 710));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchIcon.setBackground(new java.awt.Color(145, 145, 145));
        searchIcon.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        searchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchIcon.png"))); // NOI18N
        searchIcon.setBorder(null);
        searchIcon.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        searchIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchIconActionPerformed(evt);
            }
        });
        header.add(searchIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 50, 26));

        searchBar.setBackground(new java.awt.Color(145, 145, 145));
        searchBar.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        searchBar.setForeground(new java.awt.Color(229, 229, 229));
        searchBar.setText("    Search");
        searchBar.setBorder(null);
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        header.add(searchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, 26));

        profilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/men.png"))); // NOI18N
        header.add(profilePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, -1, -1));

        userName.setFont(new java.awt.Font("Questrial", 0, 12)); // NOI18N
        userName.setForeground(new java.awt.Color(0, 0, 0));
        userName.setText("Martin Berrio");
        header.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(883, 36, 70, -1));

        configArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrowProfile.png"))); // NOI18N
        header.add(configArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(946, 34, 40, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        header.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 150, 40));

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1010, 80));

        mainCont.setBackground(new java.awt.Color(102, 102, 102));
        mainCont.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabbed.addTab("tab2", activesTab);
        tabbed.addTab("tab3", completeTab);
        tabbed.addTab("tab1", allTab);

        mainCont.add(tabbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 550));

        getContentPane().add(mainCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 1010, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void searchIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchIconActionPerformed

    private void coursesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursesBtnMouseClicked
        //Cierra la ventana actual (login)
        this.dispose();
        //Abre la ventana nueva 
        cursosDashMon nuevaventana = new cursosDashMon();
        nuevaventana.setVisible(true);
    }//GEN-LAST:event_coursesBtnMouseClicked

    private void dashBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashBtnMouseClicked
        //Cierra la ventana actual (login)
        this.dispose();
        //Abre la ventana nueva 
        dashboardMon nuevaventana = new dashboardMon();
        nuevaventana.setVisible(true);    }//GEN-LAST:event_dashBtnMouseClicked

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        //Cierra la ventana actual (login)
        this.dispose();
        //Abre la ventana nueva 
        login nuevaventana = new login();
        nuevaventana.setVisible(true);
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // Abrir el perfil pasando la referencia de esta ventana (dashboard)
        profileMon nuevaventana = new profileMon(this);
        nuevaventana.setVisible(true);

        // Ocultar dashboard (no cerrarlo) para poder volver cuando el perfil cierre
        this.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void docBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseClicked
        //Cierra la ventana actual (login)
        this.dispose();
        //Abre la ventana nueva
        docente nuevaventana = new docente();
        nuevaventana.setVisible(true);
    }//GEN-LAST:event_docBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actDashMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actDashMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actDashMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actDashMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new actDashMon().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activesBtn;
    private javax.swing.JTabbedPane activesTab;
    private javax.swing.JLabel activesTxt;
    private javax.swing.JPanel actsBtn;
    private javax.swing.JLabel actsIcon;
    private javax.swing.JLabel actsTitle;
    private javax.swing.JLabel actsTxt;
    private javax.swing.JLabel allBtn;
    private javax.swing.JTabbedPane allTab;
    private javax.swing.JLabel allTxt;
    private javax.swing.JLabel appName;
    private javax.swing.JLabel completeBtn;
    private javax.swing.JTabbedPane completeTab;
    private javax.swing.JLabel completeTxt;
    private javax.swing.JLabel configArrow;
    private javax.swing.JPanel coursesBtn;
    private javax.swing.JLabel coursesIcon;
    private javax.swing.JLabel coursesTxt;
    private javax.swing.JPanel dashBtn;
    private javax.swing.JLabel dashIcon;
    private javax.swing.JLabel dashTxt;
    private javax.swing.JPanel docBtn;
    private javax.swing.JLabel docIcon;
    private javax.swing.JLabel docTxt;
    private javax.swing.JLabel filterIcon;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel listIcon;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JLabel logoutTxt;
    private javax.swing.JPanel mainCont;
    private javax.swing.JPanel menuBar;
    private javax.swing.JLabel profilePic;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton searchIcon;
    private javax.swing.JPanel sectionName;
    private javax.swing.JTabbedPane tabbed;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
