/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontMon;

import back.Actualizable;
import back.Manager;
import back.Session;
import back.Usuario;
import front.Restcontra;
import front.login;
import java.awt.Color;
import javax.swing.JOptionPane;
import main.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFrame;

/**
 *
 * @author Mi PC
 */
public class profileMon extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    private Usuario usuarioActual;
    private Restcontra ventana;
    private JFrame ventanaAnterior;

    public profileMon() {
        initComponents();
        this.usuarioActual = Manager.getUsuarioActual();
        cargarDatosUsuario();
        IDTxt.setEditable(false);
        // Mostrar aviso cuando se intente interactuar
        IDTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JOptionPane.showMessageDialog(null,
                        "El ID no se puede editar.",
                        "Message",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }
        });

    }
    
    public profileMon(JFrame ventanaAnterior) {
        initComponents();
        this.ventanaAnterior = ventanaAnterior;
        this.usuarioActual = Manager.getUsuarioActual();
        cargarDatosUsuario();
        IDTxt.setEditable(false);
        // Mostrar aviso cuando se intente interactuar
        IDTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JOptionPane.showMessageDialog(null,
                        "El ID no se puede editar.",
                        "Message",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }
        });
    }

    private void cargarDatosUsuario() {
        if (usuarioActual != null) {
            nameTxt.setText(usuarioActual.getNombre());
            lastnameTxt.setText(usuarioActual.getApellido());
            emailTxt.setText(usuarioActual.getCorreo());
            IDTxt.setText(usuarioActual.getId());
            phoneTxt.setText(usuarioActual.getTelefono());

            // Actualiza el nombre en la parte superior del perfil
            userName.setText(usuarioActual.getNombre() + " " + usuarioActual.getApellido());
        } 
    }
    private void descartarCambiosActionPerformed(java.awt.event.ActionEvent evt) {
    // Vuelve a cargar los valores originales del usuario actual
    cargarDatosUsuario();

    JOptionPane.showMessageDialog(this,
            "Los cambios han sido descartados.",
            "Message",
            JOptionPane.INFORMATION_MESSAGE
    );
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainCont = new javax.swing.JPanel();
        guardarBtn = new javax.swing.JPanel();
        guardarTxt = new javax.swing.JLabel();
        restablecerBtn = new javax.swing.JPanel();
        restablecerTxt = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JPanel();
        deleteTxt = new javax.swing.JLabel();
        saveBtn = new javax.swing.JPanel();
        saveTxt = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        phoneTitle = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        IDTitle = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        emailTitle = new javax.swing.JLabel();
        lastnameTxt = new javax.swing.JTextField();
        lastnameTitle = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        nameTitle = new javax.swing.JLabel();
        mainShadow = new javax.swing.JLabel();
        menuBar = new javax.swing.JPanel();
        appName = new javax.swing.JLabel();
        infoBtn = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        profileData = new javax.swing.JPanel();
        backBtn = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JPanel();
        logoutTxt = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        headerTitle = new javax.swing.JLabel();
        headerShadow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainCont.setBackground(new java.awt.Color(255, 255, 255));
        mainCont.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guardarBtn.setBackground(new java.awt.Color(64, 174, 178));
        guardarBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                guardarBtnMouseMoved(evt);
            }
        });
        guardarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guardarBtnMouseExited(evt);
            }
        });
        guardarBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guardarTxt.setBackground(new java.awt.Color(247, 247, 247));
        guardarTxt.setFont(new java.awt.Font("Questrial", 0, 18)); // NOI18N
        guardarTxt.setForeground(new java.awt.Color(255, 255, 255));
        guardarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guardarTxt.setText("Guardar contraseña");
        guardarTxt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                guardarTxtMouseMoved(evt);
            }
        });
        guardarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarTxtMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guardarTxtMouseExited(evt);
            }
        });
        guardarBtn.add(guardarTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 50));

        mainCont.add(guardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 280, 50));

        restablecerBtn.setBackground(new java.awt.Color(221, 224, 229));
        restablecerBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                restablecerBtnMouseMoved(evt);
            }
        });
        restablecerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restablecerBtnMouseExited(evt);
            }
        });
        restablecerBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        restablecerTxt.setBackground(new java.awt.Color(247, 247, 247));
        restablecerTxt.setFont(new java.awt.Font("Questrial", 0, 18)); // NOI18N
        restablecerTxt.setForeground(new java.awt.Color(255, 255, 255));
        restablecerTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        restablecerTxt.setText("Restablecer contraseña");
        restablecerTxt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                restablecerTxtMouseMoved(evt);
            }
        });
        restablecerTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restablecerTxtMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restablecerTxtMouseExited(evt);
            }
        });
        restablecerBtn.add(restablecerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 50));

        mainCont.add(restablecerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 280, 50));

        deleteBtn.setBackground(new java.awt.Color(247, 247, 247));
        deleteBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 174, 178), 2));
        deleteBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                deleteBtnMouseMoved(evt);
            }
        });
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBtnMouseExited(evt);
            }
        });
        deleteBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteTxt.setBackground(new java.awt.Color(247, 247, 247));
        deleteTxt.setFont(new java.awt.Font("Questrial", 0, 18)); // NOI18N
        deleteTxt.setForeground(new java.awt.Color(64, 174, 178));
        deleteTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteTxt.setText("Descartar cambios");
        deleteTxt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                deleteTxtMouseMoved(evt);
            }
        });
        deleteTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteTxtMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteTxtMouseExited(evt);
            }
        });
        deleteBtn.add(deleteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 50));

        mainCont.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 240, 50));

        saveBtn.setBackground(new java.awt.Color(4, 174, 178));
        saveBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                saveBtnMouseMoved(evt);
            }
        });
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveBtnMouseExited(evt);
            }
        });
        saveBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saveTxt.setFont(new java.awt.Font("Questrial", 0, 18)); // NOI18N
        saveTxt.setForeground(new java.awt.Color(255, 255, 255));
        saveTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveTxt.setText("Guardar cambios");
        saveBtn.add(saveTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 50));

        mainCont.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 240, 50));

        phoneTxt.setBackground(new java.awt.Color(255, 255, 255));
        phoneTxt.setForeground(new java.awt.Color(102, 102, 102));
        phoneTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTxtActionPerformed(evt);
            }
        });
        mainCont.add(phoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 210, 33));

        phoneTitle.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        phoneTitle.setForeground(new java.awt.Color(0, 0, 0));
        phoneTitle.setText("Celular");
        mainCont.add(phoneTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        IDTxt.setBackground(new java.awt.Color(255, 255, 255));
        IDTxt.setForeground(new java.awt.Color(102, 102, 102));
        IDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTxtActionPerformed(evt);
            }
        });
        mainCont.add(IDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 210, 33));

        IDTitle.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        IDTitle.setForeground(new java.awt.Color(0, 0, 0));
        IDTitle.setText("ID Estudiantil");
        mainCont.add(IDTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 20));

        emailTxt.setBackground(new java.awt.Color(255, 255, 255));
        emailTxt.setForeground(new java.awt.Color(102, 102, 102));
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        mainCont.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 790, 33));

        emailTitle.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        emailTitle.setForeground(new java.awt.Color(0, 0, 0));
        emailTitle.setText("E-mail");
        mainCont.add(emailTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lastnameTxt.setBackground(new java.awt.Color(255, 255, 255));
        lastnameTxt.setForeground(new java.awt.Color(102, 102, 102));
        mainCont.add(lastnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 310, 33));

        lastnameTitle.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        lastnameTitle.setForeground(new java.awt.Color(0, 0, 0));
        lastnameTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastnameTitle.setText("Apellidos");
        mainCont.add(lastnameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 70, -1));

        nameTxt.setBackground(new java.awt.Color(255, 255, 255));
        nameTxt.setForeground(new java.awt.Color(102, 102, 102));
        mainCont.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 330, 33));

        nameTitle.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        nameTitle.setForeground(new java.awt.Color(0, 0, 0));
        nameTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameTitle.setText("Nombres");
        mainCont.add(nameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        mainShadow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bodyInfo.png"))); // NOI18N
        mainCont.add(mainShadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 996, 537));

        getContentPane().add(mainCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 1010, 600));

        menuBar.setBackground(new java.awt.Color(255, 255, 255));
        menuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        appName.setFont(new java.awt.Font("Questrial", 0, 30)); // NOI18N
        appName.setForeground(new java.awt.Color(0, 0, 0));
        appName.setText("Skillbridge");
        menuBar.add(appName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        infoBtn.setBackground(new java.awt.Color(255, 255, 255));
        infoBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(64, 174, 178));
        jLabel8.setText("Información");
        infoBtn.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrowInfo.png"))); // NOI18N
        infoBtn.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        menuBar.add(infoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 260, 40));

        profileData.setBackground(new java.awt.Color(255, 255, 255));
        profileData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });
        backBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Retroceder");
        backBtn.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 10));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backIcon.png"))); // NOI18N
        backBtn.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        profileData.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 0, 150, 30));

        jLabel5.setFont(new java.awt.Font("Questrial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(145, 145, 145));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Monitor");
        profileData.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 193, 70, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profilePic.png"))); // NOI18N
        profileData.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 123, 123));

        userName.setFont(new java.awt.Font("Questrial", 0, 16)); // NOI18N
        userName.setForeground(new java.awt.Color(0, 0, 0));
        userName.setText("Martín Berrío");
        profileData.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 176, -1, -1));

        menuBar.add(profileData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 260, 250));

        logoutBtn.setBackground(new java.awt.Color(255, 255, 255));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });
        logoutBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutTxt.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        logoutTxt.setForeground(new java.awt.Color(0, 0, 0));
        logoutTxt.setText("Log out");
        logoutBtn.add(logoutTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 13, -1, -1));

        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoutIcon.png"))); // NOI18N
        logoutBtn.add(logoutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        menuBar.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 260, 40));

        getContentPane().add(menuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 710));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerTitle.setFont(new java.awt.Font("Questrial", 0, 35)); // NOI18N
        headerTitle.setForeground(new java.awt.Color(0, 0, 0));
        headerTitle.setText("Información personal");
        header.add(headerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 440, -1));

        headerShadow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/headerInfo.png"))); // NOI18N
        header.add(headerShadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 996, 70));

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1010, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void IDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTxtActionPerformed

    private void phoneTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTxtActionPerformed

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        //Cierra la ventana actual (login)
        this.dispose();
        //Abre la ventana nueva
        login nuevaventana = new login();
        nuevaventana.setVisible(true);
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void saveBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseMoved
        saveBtn.setBackground(new Color(38, 114, 116));
    }//GEN-LAST:event_saveBtnMouseMoved

    private void saveBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseExited
        saveBtn.setBackground(new Color(4, 174, 178));

    }//GEN-LAST:event_saveBtnMouseExited

    private void guardarBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBtnMouseMoved
        guardarBtn.setBackground(new Color(38, 114, 116));

    }//GEN-LAST:event_guardarBtnMouseMoved

    private void guardarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBtnMouseExited
        guardarBtn.setBackground(new Color(4, 174, 178));

    }//GEN-LAST:event_guardarBtnMouseExited

    private void restablecerBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restablecerBtnMouseMoved
        restablecerBtn.setBackground(new Color(145, 145, 145));

    }//GEN-LAST:event_restablecerBtnMouseMoved

    private void restablecerBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restablecerBtnMouseExited
        restablecerBtn.setBackground(new Color(221, 224, 229));

    }//GEN-LAST:event_restablecerBtnMouseExited

    private void restablecerTxtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restablecerTxtMouseMoved
        restablecerBtn.setBackground(new Color(145, 145, 145));
    }//GEN-LAST:event_restablecerTxtMouseMoved

    private void deleteTxtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteTxtMouseMoved
        deleteBtn.setBackground(new Color(4, 174, 178));
        deleteTxt.setForeground(new Color(255, 255, 255));

    }//GEN-LAST:event_deleteTxtMouseMoved

    private void deleteTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteTxtMouseExited
        deleteBtn.setBackground(new Color(247, 247, 247));
        deleteTxt.setForeground(new Color(4, 174, 178));

    }//GEN-LAST:event_deleteTxtMouseExited

    private void deleteBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseMoved
        deleteBtn.setBackground(new Color(4, 174, 178));
        deleteTxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_deleteBtnMouseMoved

    private void deleteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseExited
        deleteBtn.setBackground(new Color(247, 247, 247));
        deleteTxt.setForeground(new Color(4, 174, 178));

    }//GEN-LAST:event_deleteBtnMouseExited

    private void restablecerTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restablecerTxtMouseExited
        restablecerBtn.setBackground(new Color(221, 224, 229));
    }//GEN-LAST:event_restablecerTxtMouseExited

    private void saveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseClicked
        // TODO add your handling code here:
        if (usuarioActual != null) {
            String nuevoNombre = nameTxt.getText();
            String nuevoApellido = lastnameTxt.getText();
            String nuevoCorreo = emailTxt.getText();
            String nuevoTelefono = phoneTxt.getText();
            String id = usuarioActual.getId();

            boolean exito = usuarioActual.actualizarUsuarioSQLite(id, nuevoNombre, nuevoApellido, nuevoCorreo, nuevoTelefono);

            if (exito) {
                JOptionPane.showMessageDialog(this, "✅ Datos actualizados correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "❌ No se pudo actualizar la información.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "⚠️ No hay usuario cargado.");
        }
        // Actualiza el objeto usuarioActual con los nuevos datos
        usuarioActual.setNombre(nameTxt.getText());
        usuarioActual.setApellido(lastnameTxt.getText());
        usuarioActual.setCorreo(emailTxt.getText());
        usuarioActual.setId(IDTxt.getText());
        usuarioActual.setTelefono(phoneTxt.getText());

        // Actualiza el nombre debajo de la foto de perfil
        userName.setText(usuarioActual.getNombre() + " " + usuarioActual.getApellido());


    }//GEN-LAST:event_saveBtnMouseClicked

    private void restablecerTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restablecerTxtMouseClicked
        // TODO add your handling code here:
        ventana = new Restcontra();
        ventana.setLocation(550, 250);// ← GUARDA LA VENTANA AQUÍ
        ventana.setVisible(true);
    }//GEN-LAST:event_restablecerTxtMouseClicked

    private void guardarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarTxtMouseClicked

        if (ventana == null) {
            JOptionPane.showMessageDialog(this, "⚠ Primero abre la ventana de restablecer contraseña.");
            return;
        }

        ventana.recogerDatos();

        String actual = ventana.getActual();
        String nueva = ventana.getNueva();
        String repetir = ventana.getRepetir();

        Usuario u = Session.getUsuario();

        // Validar contraseña actual
        if (!u.getContraseña().equals(actual)) {
            JOptionPane.showMessageDialog(this, "⚠ La contraseña actual es incorrecta.");
            return;
        }

        // Validar coincidencia
        if (!nueva.equals(repetir)) {
            JOptionPane.showMessageDialog(this, "⚠ Las nuevas contraseñas no coinciden.");
            return;
        }

        // Cambiar en el objeto
        u.setContraseña(nueva);

        // Guardar en BD
        try (Connection conn = DBConnection.getConnection()) {
            String sql = "UPDATE usuarios SET contraseña = ? WHERE id = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, nueva);
            ps.setString(2, String.valueOf(u.getId()));

            ps.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar en la base de datos: " + e.getMessage());
            return;
        }

        JOptionPane.showMessageDialog(this, "Contraseña actualizada correctamente.");

        ventana.dispose();
        ventana = null;


    }//GEN-LAST:event_guardarTxtMouseClicked

    private void guardarTxtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarTxtMouseMoved
        guardarBtn.setBackground(new Color(38, 114, 116));

    }//GEN-LAST:event_guardarTxtMouseMoved

    private void guardarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarTxtMouseExited
        guardarBtn.setBackground(new Color(4, 174, 178));


    }//GEN-LAST:event_guardarTxtMouseExited

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
       if (ventanaAnterior != null) {

            // 1. Verificamos si la ventana anterior implementa la interfaz Actualizable.
            if (ventanaAnterior instanceof Actualizable) {

                // 2. Si lo hace, hacemos el casting a la interfaz y llamamos al método.
                ((Actualizable) ventanaAnterior).actualizarNombreEnUI();

                System.out.println("✅ Ventana Anterior notificada para recargar el nombre.");
            }

            // 3. Hacemos visible la ventana anterior (ya actualizada).
            ventanaAnterior.setVisible(true);
        }

        // 4. Cerrar la ventana de perfil (solo una vez).
        this.dispose();
     // ⬅️ Fin del método backBtnMouseClicked.
    
    }//GEN-LAST:event_backBtnMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void deleteTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteTxtMouseClicked
        descartarCambiosActionPerformed(null);
    }//GEN-LAST:event_deleteTxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profileMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profileMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profileMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profileMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new profileMon().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDTitle;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JLabel appName;
    private javax.swing.JPanel backBtn;
    private javax.swing.JPanel deleteBtn;
    private javax.swing.JLabel deleteTxt;
    private javax.swing.JLabel emailTitle;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JPanel guardarBtn;
    private javax.swing.JLabel guardarTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel headerShadow;
    private javax.swing.JLabel headerTitle;
    private javax.swing.JPanel infoBtn;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lastnameTitle;
    private javax.swing.JTextField lastnameTxt;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JLabel logoutTxt;
    private javax.swing.JPanel mainCont;
    private javax.swing.JLabel mainShadow;
    private javax.swing.JPanel menuBar;
    private javax.swing.JLabel nameTitle;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel phoneTitle;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JPanel profileData;
    private javax.swing.JPanel restablecerBtn;
    private javax.swing.JLabel restablecerTxt;
    private javax.swing.JPanel saveBtn;
    private javax.swing.JLabel saveTxt;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
