/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Actividades;

/**
 *
 * @author Mi PC
 */
public class act extends javax.swing.JPanel {

    /**
     * Creates new form act
     */
    public act() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        videoTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        videoTitle1 = new javax.swing.JLabel();
        asigBtn = new javax.swing.JPanel();
        asigName = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        videoTitle.setFont(new java.awt.Font("Questrial", 0, 14)); // NOI18N
        videoTitle.setForeground(new java.awt.Color(0, 0, 0));
        videoTitle.setText("Autor");
        jPanel1.add(videoTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jPanel2.setBackground(new java.awt.Color(64, 174, 178));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 20, 180, 130));

        videoTitle1.setFont(new java.awt.Font("Questrial", 1, 18)); // NOI18N
        videoTitle1.setForeground(new java.awt.Color(0, 0, 0));
        videoTitle1.setText("Actividad");
        jPanel1.add(videoTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        asigBtn.setBackground(new java.awt.Color(221, 224, 229));

        asigName.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        asigName.setForeground(new java.awt.Color(145, 145, 145));
        asigName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asigName.setText("Asignatura");

        javax.swing.GroupLayout asigBtnLayout = new javax.swing.GroupLayout(asigBtn);
        asigBtn.setLayout(asigBtnLayout);
        asigBtnLayout.setHorizontalGroup(
            asigBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asigBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(asigName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        asigBtnLayout.setVerticalGroup(
            asigBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asigName, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel1.add(asigBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 80, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 220));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel asigBtn;
    private javax.swing.JLabel asigName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel videoTitle;
    private javax.swing.JLabel videoTitle1;
    // End of variables declaration//GEN-END:variables
}
