/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;


import back.Manager;
import back.Session;
import java.awt.Color;
import frontEs.dashboard;
import frontMon.dashboardMon;
import back.Usuario;

/**
 *
 * @author Mi PC
 */

public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(bc, "src/images/bc.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registrar = new javax.swing.JPanel();
        registrarTxt = new javax.swing.JLabel();
        Acceder = new javax.swing.JPanel();
        accederTxt = new javax.swing.JLabel();
        lockIcon = new javax.swing.JLabel();
        IDIcon = new javax.swing.JLabel();
        aTitle = new javax.swing.JLabel();
        blackMarker = new javax.swing.JLabel();
        starSmall = new javax.swing.JLabel();
        starBig = new javax.swing.JLabel();
        womanPic = new javax.swing.JLabel();
        manPic = new javax.swing.JLabel();
        shadow2 = new javax.swing.JLabel();
        shadow1 = new javax.swing.JLabel();
        passLine = new javax.swing.JSeparator();
        passTxt = new javax.swing.JPasswordField();
        IDLine = new javax.swing.JSeparator();
        IDTxt = new javax.swing.JTextField();
        logoBlack = new javax.swing.JLabel();
        appName = new javax.swing.JLabel();
        bTitle = new javax.swing.JLabel();
        ienvenidoTitle = new javax.swing.JLabel();
        loginBtn = new javax.swing.JLabel();
        signupBtn = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        skillbridgeName = new javax.swing.JLabel();
        greenBoard = new javax.swing.JLabel();
        whiteBoard = new javax.swing.JLabel();
        bc = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Registrar.setBackground(new java.awt.Color(4, 174, 178));
        Registrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                RegistrarMouseMoved(evt);
            }
        });
        Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistrarMouseExited(evt);
            }
        });
        Registrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrarTxt.setFont(new java.awt.Font("Questrial", 0, 14)); // NOI18N
        registrarTxt.setForeground(new java.awt.Color(255, 255, 255));
        registrarTxt.setText("Registrar");
        Registrar.add(registrarTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 60, -1));

        getContentPane().add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 550, 210, 40));

        Acceder.setBackground(new java.awt.Color(4, 174, 178));
        Acceder.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AccederMouseMoved(evt);
            }
        });
        Acceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccederMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AccederMouseExited(evt);
            }
        });
        Acceder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accederTxt.setFont(new java.awt.Font("Questrial", 0, 14)); // NOI18N
        accederTxt.setForeground(new java.awt.Color(255, 255, 255));
        accederTxt.setText("Acceder");
        Acceder.add(accederTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        getContentPane().add(Acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 490, 210, 40));

        lockIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lockIcon.png"))); // NOI18N
        getContentPane().add(lockIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, 30, 30));

        IDIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/idIcon.png"))); // NOI18N
        getContentPane().add(IDIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 30, 30));

        aTitle.setFont(new java.awt.Font("Questrial", 0, 51)); // NOI18N
        aTitle.setForeground(new java.awt.Color(0, 0, 0));
        aTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aTitle.setText("a");
        getContentPane().add(aTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 40, -1));

        blackMarker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blackMarker.png"))); // NOI18N
        getContentPane().add(blackMarker, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 256, -1, -1));

        starSmall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starSmall.png"))); // NOI18N
        starSmall.setText("jLabel12");
        getContentPane().add(starSmall, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 64, 63));

        starBig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starBig.png"))); // NOI18N
        getContentPane().add(starBig, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 141, 138));

        womanPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/woman.png"))); // NOI18N
        womanPic.setText("jLabel7");
        getContentPane().add(womanPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 398, 337));

        manPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N
        getContentPane().add(manPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 256, 308));

        shadow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greenShadow2.png"))); // NOI18N
        shadow2.setText("jLabel10");
        getContentPane().add(shadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 271, 110));

        shadow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greenShadow.png"))); // NOI18N
        shadow1.setText("jLabel9");
        getContentPane().add(shadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 158, 64));

        passLine.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(passLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 450, 210, 10));

        passTxt.setBackground(new java.awt.Color(255, 255, 255));
        passTxt.setForeground(new java.awt.Color(153, 153, 153));
        passTxt.setText("Password");
        passTxt.setBorder(null);
        passTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTxtMousePressed(evt);
            }
        });
        getContentPane().add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 428, 180, -1));

        IDLine.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(IDLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 360, 210, 10));

        IDTxt.setBackground(new java.awt.Color(255, 255, 255));
        IDTxt.setForeground(new java.awt.Color(153, 153, 153));
        IDTxt.setText("ID");
        IDTxt.setBorder(null);
        IDTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IDTxtMousePressed(evt);
            }
        });
        IDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTxtActionPerformed(evt);
            }
        });
        getContentPane().add(IDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 338, 180, -1));

        logoBlack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoBlack.png"))); // NOI18N
        getContentPane().add(logoBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 140, 120, 80));

        appName.setFont(new java.awt.Font("Questrial", 1, 66)); // NOI18N
        appName.setForeground(new java.awt.Color(0, 0, 0));
        appName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appName.setText("Skillbridge");
        getContentPane().add(appName, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 330, -1));

        bTitle.setFont(new java.awt.Font("Questrial", 0, 66)); // NOI18N
        bTitle.setForeground(new java.awt.Color(255, 255, 255));
        bTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bTitle.setText("B");
        getContentPane().add(bTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 120, -1, 90));

        ienvenidoTitle.setFont(new java.awt.Font("Questrial", 0, 66)); // NOI18N
        ienvenidoTitle.setForeground(new java.awt.Color(0, 0, 0));
        ienvenidoTitle.setText("ienvenido");
        getContentPane().add(ienvenidoTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 290, 90));

        loginBtn.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        signupBtn.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        signupBtn.setForeground(new java.awt.Color(255, 255, 255));
        signupBtn.setText("Sign Up");
        getContentPane().add(signupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 90, 30));

        skillbridgeName.setFont(new java.awt.Font("Questrial", 0, 36)); // NOI18N
        skillbridgeName.setForeground(new java.awt.Color(255, 255, 255));
        skillbridgeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        skillbridgeName.setText("SkillBridge");
        getContentPane().add(skillbridgeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 180, 50));

        greenBoard.setBackground(new java.awt.Color(255, 255, 255));
        greenBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greenBoard.png"))); // NOI18N
        getContentPane().add(greenBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1210, 710));

        whiteBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteBoard.png"))); // NOI18N
        getContentPane().add(whiteBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1290, 710));

        bc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bc.png"))); // NOI18N
        getContentPane().add(bc, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 1290, 710));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTxtActionPerformed

    private void AccederMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccederMouseMoved
        Acceder.setBackground(new Color(38, 114, 116));
    }//GEN-LAST:event_AccederMouseMoved

    private void AccederMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccederMouseExited

        Acceder.setBackground(new Color(4, 174, 178));

    }//GEN-LAST:event_AccederMouseExited

    private void RegistrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseMoved
        Registrar.setBackground(new Color(38, 114, 116));

    }//GEN-LAST:event_RegistrarMouseMoved

    private void RegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseExited
        Registrar.setBackground(new Color(4, 174, 178));
    }//GEN-LAST:event_RegistrarMouseExited

    private void RegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseClicked
        //Cierra la ventana actual (login)
        this.dispose();
        //Abre la ventana nueva 
        signup nuevaventana = new signup();
        nuevaventana.setVisible(true);
    }//GEN-LAST:event_RegistrarMouseClicked

    private void AccederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccederMouseClicked
        //Cierra la ventana actual (login)
        //  this.dispose();
        //Abre la ventana nueva 
        //dashboard nuevaventana = new dashboard(); 
        //nuevaventana.setVisible(true);                                                                  
        String idTexto = IDTxt.getText().trim();
        String contraseña = new String(passTxt.getPassword()).trim();

        // Crear instancia de Usuario
        Usuario usuario = new Usuario();

        // Validar datos
        if (!usuario.validarLoginPorID(idTexto, contraseña)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "❌ Usuario o contraseña incorrectos.");
            passTxt.setText("");
            return;
        }

        // Guardar el usuario actual
        Session.setUsuario(usuario);

        Manager.setUsuarioActual(usuario);

        javax.swing.JOptionPane.showMessageDialog(this,
                "✅ Bienvenido " + usuario.getNombre() + " (" + usuario.getRol() + ")");

        this.dispose(); // Cerrar login

        // Redirigir según el rol
        String rol = usuario.getRol();

        if ("Estudiante".equalsIgnoreCase(rol)) {
            new dashboard().setVisible(true);

        } else if ("Monitor/tutor".equalsIgnoreCase(rol)) {
            new dashboardMon().setVisible(true);

        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "⚠️ Rol desconocido. Contacte al administrador.");
        }
   
    }//GEN-LAST:event_AccederMouseClicked

    private void IDTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDTxtMousePressed
        if (IDTxt.getText().equals("ID")) {
            IDTxt.setText("");
        }

        if (String.valueOf(passTxt.getPassword()).isEmpty()) {
            passTxt.setText("Password");
        }
    }//GEN-LAST:event_IDTxtMousePressed

    private void passTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMousePressed
        if (String.valueOf(passTxt.getPassword()).equals("Password")) {
            passTxt.setText("");
        }

        if (IDTxt.getText().isEmpty()) {
            IDTxt.setText("ID");
        }
    }//GEN-LAST:event_passTxtMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new login().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acceder;
    private javax.swing.JLabel IDIcon;
    private javax.swing.JSeparator IDLine;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JPanel Registrar;
    private javax.swing.JLabel aTitle;
    private javax.swing.JLabel accederTxt;
    private javax.swing.JLabel appName;
    private javax.swing.JLabel bTitle;
    private javax.swing.JLabel bc;
    private javax.swing.JLabel blackMarker;
    private javax.swing.JLabel greenBoard;
    private javax.swing.JLabel ienvenidoTitle;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lockIcon;
    private javax.swing.JLabel loginBtn;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoBlack;
    private javax.swing.JLabel manPic;
    private javax.swing.JSeparator passLine;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JLabel registrarTxt;
    private javax.swing.JLabel shadow1;
    private javax.swing.JLabel shadow2;
    private javax.swing.JLabel signupBtn;
    private javax.swing.JLabel skillbridgeName;
    private javax.swing.JLabel starBig;
    private javax.swing.JLabel starSmall;
    private javax.swing.JLabel whiteBoard;
    private javax.swing.JLabel womanPic;
    // End of variables declaration//GEN-END:variables
}
