/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;

import back.Session;
import back.Usuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import main.DBConnection;

/**
 *
 * @author PC
 */

public class Restcontra extends javax.swing.JFrame {

    private String actual;
    private String nueva;
    private String repetir;
    private boolean listo = false;

    public Restcontra() {
        initComponents();
    }


    // Métodos para que PROFILE lea los datos
    public String getActual() {
        return new String(passActualTxt.getPassword());
    }

    public String getNueva() {
        return new String(passNewTxt.getPassword());
    }

    public String getRepetir() {
        return new String(passAgainTxt.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grayPane = new javax.swing.JPanel();
        passActualTitle = new javax.swing.JLabel();
        passNewTitle = new javax.swing.JLabel();
        passAgainTitle = new javax.swing.JLabel();
        passActualTxt = new javax.swing.JPasswordField();
        passNewTxt = new javax.swing.JPasswordField();
        passAgainTxt = new javax.swing.JPasswordField();
        exitBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        grayPane.setBackground(new java.awt.Color(145, 145, 145));
        grayPane.setMaximumSize(null);

        passActualTitle.setFont(new java.awt.Font("Questrial", 1, 14)); // NOI18N
        passActualTitle.setForeground(new java.awt.Color(255, 255, 255));
        passActualTitle.setText("Contraseña actual");

        passNewTitle.setFont(new java.awt.Font("Questrial", 1, 14)); // NOI18N
        passNewTitle.setForeground(new java.awt.Color(255, 255, 255));
        passNewTitle.setText("Contraseña nueva");

        passAgainTitle.setFont(new java.awt.Font("Questrial", 1, 14)); // NOI18N
        passAgainTitle.setForeground(new java.awt.Color(255, 255, 255));
        passAgainTitle.setText("Repetir contraseña");

        passActualTxt.setBackground(new java.awt.Color(247, 247, 247));
        passActualTxt.setForeground(new java.awt.Color(153, 153, 153));
        passActualTxt.setText("Password");
        passActualTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passActualTxtMousePressed(evt);
            }
        });
        passActualTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActualTxtActionPerformed(evt);
            }
        });

        passNewTxt.setBackground(new java.awt.Color(247, 247, 247));
        passNewTxt.setForeground(new java.awt.Color(153, 153, 153));
        passNewTxt.setText("Password");
        passNewTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passNewTxtMousePressed(evt);
            }
        });

        passAgainTxt.setBackground(new java.awt.Color(247, 247, 247));
        passAgainTxt.setForeground(new java.awt.Color(153, 153, 153));
        passAgainTxt.setText("Password");
        passAgainTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passAgainTxtMousePressed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Questrial", 1, 12)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitBtn.setText("X");
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout grayPaneLayout = new javax.swing.GroupLayout(grayPane);
        grayPane.setLayout(grayPaneLayout);
        grayPaneLayout.setHorizontalGroup(
            grayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grayPaneLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(grayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passAgainTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passAgainTitle)
                    .addComponent(passNewTitle)
                    .addComponent(passActualTitle)
                    .addComponent(passActualTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passNewTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grayPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        grayPaneLayout.setVerticalGroup(
            grayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grayPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitBtn)
                .addGap(1, 1, 1)
                .addComponent(passActualTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passActualTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passNewTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passNewTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passAgainTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passAgainTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grayPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grayPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passActualTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActualTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActualTxtActionPerformed

    private void passActualTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passActualTxtMousePressed
        if (String.valueOf(passActualTxt.getPassword()).equals("Password")) {
            passActualTxt.setText("");
        }
    }//GEN-LAST:event_passActualTxtMousePressed

    private void passNewTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passNewTxtMousePressed
        if (String.valueOf(passNewTxt.getPassword()).equals("Password")) {
            passNewTxt.setText("");
        }
    }//GEN-LAST:event_passNewTxtMousePressed

    private void passAgainTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passAgainTxtMousePressed
        if (String.valueOf(passAgainTxt.getPassword()).equals("Password")) {
            passAgainTxt.setText("");
        }
    }//GEN-LAST:event_passAgainTxtMousePressed

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitBtnMouseClicked

    public void recogerDatos() {
    actual = new String(passActualTxt.getPassword());
    nueva = new String(passNewTxt.getPassword());
    repetir = new String(passAgainTxt.getPassword());

    // NO validar aquí
    // NO cerrar la ventana
    // NO mostrar mensajes
    listo = true;
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Restcontra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Restcontra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Restcontra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Restcontra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Restcontra().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitBtn;
    private javax.swing.JPanel grayPane;
    private javax.swing.JLabel passActualTitle;
    private javax.swing.JPasswordField passActualTxt;
    private javax.swing.JLabel passAgainTitle;
    private javax.swing.JPasswordField passAgainTxt;
    private javax.swing.JLabel passNewTitle;
    private javax.swing.JPasswordField passNewTxt;
    // End of variables declaration//GEN-END:variables
}
