/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;

import back.Usuario;
import front.login;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Mi PC
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public signup() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(bc, "src/images/bc.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. holiiiiiiiiiiii
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rolTitle = new javax.swing.JLabel();
        rolTxt = new javax.swing.JComboBox<>();
        starMini = new javax.swing.JLabel();
        passTxt = new javax.swing.JPasswordField();
        registrarBtn = new javax.swing.JPanel();
        registrarTxt = new javax.swing.JLabel();
        arrow = new javax.swing.JLabel();
        passTitle = new javax.swing.JLabel();
        phraseStart = new javax.swing.JLabel();
        gradHatsmall = new javax.swing.JLabel();
        gradHatbig = new javax.swing.JLabel();
        woman2 = new javax.swing.JLabel();
        woman1 = new javax.swing.JLabel();
        manGrad = new javax.swing.JLabel();
        starBig = new javax.swing.JLabel();
        passAgaintxt = new javax.swing.JPasswordField();
        passAgaintitle = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        phoneTitle = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        IDTitle = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        emailTitle = new javax.swing.JLabel();
        lastnameTxt = new javax.swing.JTextField();
        lastnameTitle = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        nameTitle = new javax.swing.JLabel();
        aTitle = new javax.swing.JLabel();
        logoWhite = new javax.swing.JLabel();
        appName = new javax.swing.JLabel();
        blackMarker = new javax.swing.JLabel();
        bienvenidoTitle = new javax.swing.JLabel();
        loginBtn = new javax.swing.JLabel();
        signupBtn = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        skillbridgeName = new javax.swing.JLabel();
        greenBoard = new javax.swing.JLabel();
        whiteBoard = new javax.swing.JLabel();
        bc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rolTitle.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        rolTitle.setForeground(new java.awt.Color(102, 102, 102));
        rolTitle.setText("Rol");
        getContentPane().add(rolTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, -1, -1));

        rolTxt.setBackground(new java.awt.Color(255, 255, 255));
        rolTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Monitor/tutor" }));
        rolTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolTxtActionPerformed(evt);
            }
        });
        getContentPane().add(rolTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 310, 30));

        starMini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star3.png"))); // NOI18N
        starMini.setText("jLabel20");
        getContentPane().add(starMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 57, 56));

        passTxt.setBackground(new java.awt.Color(247, 247, 247));
        passTxt.setForeground(new java.awt.Color(153, 153, 153));
        passTxt.setText("Password");
        passTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTxtMousePressed(evt);
            }
        });
        getContentPane().add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 270, 30));

        registrarBtn.setBackground(new java.awt.Color(4, 174, 178));
        registrarBtn.setForeground(new java.awt.Color(4, 174, 178));
        registrarBtn.setAutoscrolls(true);
        registrarBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                registrarBtnMouseMoved(evt);
            }
        });
        registrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarBtnMouseExited(evt);
            }
        });
        registrarBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrarTxt.setFont(new java.awt.Font("Questrial", 0, 14)); // NOI18N
        registrarTxt.setForeground(new java.awt.Color(255, 255, 255));
        registrarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarTxt.setText("Registrar");
        registrarBtn.add(registrarTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 40));

        getContentPane().add(registrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 560, 210, 40));

        arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        getContentPane().add(arrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 540, 96, 60));

        passTitle.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        passTitle.setForeground(new java.awt.Color(102, 102, 102));
        passTitle.setText("Contraseña");
        getContentPane().add(passTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, -1, -1));

        phraseStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/phrase.png"))); // NOI18N
        getContentPane().add(phraseStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 210, 86));

        gradHatsmall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hat2.png"))); // NOI18N
        gradHatsmall.setText("jLabel17");
        getContentPane().add(gradHatsmall, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 123, 195));

        gradHatbig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hat1.png"))); // NOI18N
        gradHatbig.setText("jLabel16");
        getContentPane().add(gradHatbig, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 218, 344));

        woman2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/w1.png"))); // NOI18N
        getContentPane().add(woman2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 124, 125, 150));

        woman1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/w2.png"))); // NOI18N
        getContentPane().add(woman1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 134, 120, 139));

        manGrad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manGrad.png"))); // NOI18N
        manGrad.setText("jLabel12");
        getContentPane().add(manGrad, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 330, 309, 380));

        starBig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star2.png"))); // NOI18N
        getContentPane().add(starBig, new org.netbeans.lib.awtextra.AbsoluteConstraints(1004, 380, 100, 100));

        passAgaintxt.setBackground(new java.awt.Color(247, 247, 247));
        passAgaintxt.setForeground(new java.awt.Color(153, 153, 153));
        passAgaintxt.setText("Password");
        passAgaintxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passAgaintxtMousePressed(evt);
            }
        });
        getContentPane().add(passAgaintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 270, 30));

        passAgaintitle.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        passAgaintitle.setForeground(new java.awt.Color(102, 102, 102));
        passAgaintitle.setText("Repetir contraseña");
        getContentPane().add(passAgaintitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, -1, 20));

        phoneTxt.setBackground(new java.awt.Color(247, 247, 247));
        phoneTxt.setForeground(new java.awt.Color(102, 102, 102));
        phoneTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTxtActionPerformed(evt);
            }
        });
        getContentPane().add(phoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 210, 33));

        phoneTitle.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        phoneTitle.setForeground(new java.awt.Color(102, 102, 102));
        phoneTitle.setText("Celular");
        getContentPane().add(phoneTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, -1, -1));

        IDTxt.setBackground(new java.awt.Color(247, 247, 247));
        IDTxt.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(IDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 210, 33));

        IDTitle.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        IDTitle.setForeground(new java.awt.Color(102, 102, 102));
        IDTitle.setText("ID Estudiantil");
        getContentPane().add(IDTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));

        emailTxt.setBackground(new java.awt.Color(247, 247, 247));
        emailTxt.setForeground(new java.awt.Color(102, 102, 102));
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        getContentPane().add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 330, 33));

        emailTitle.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        emailTitle.setForeground(new java.awt.Color(102, 102, 102));
        emailTitle.setText("E-mail");
        getContentPane().add(emailTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        lastnameTxt.setBackground(new java.awt.Color(247, 247, 247));
        lastnameTxt.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(lastnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 310, 33));

        lastnameTitle.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        lastnameTitle.setForeground(new java.awt.Color(102, 102, 102));
        lastnameTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastnameTitle.setText("Apellidos");
        getContentPane().add(lastnameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 70, -1));

        nameTxt.setBackground(new java.awt.Color(247, 247, 247));
        nameTxt.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 330, 33));

        nameTitle.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        nameTitle.setForeground(new java.awt.Color(102, 102, 102));
        nameTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameTitle.setText("Nombres");
        getContentPane().add(nameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        aTitle.setFont(new java.awt.Font("Questrial", 0, 51)); // NOI18N
        aTitle.setForeground(new java.awt.Color(255, 255, 255));
        aTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aTitle.setText("a");
        getContentPane().add(aTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 40, -1));

        logoWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteLogo.png"))); // NOI18N
        getContentPane().add(logoWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 140, 120, 80));

        appName.setFont(new java.awt.Font("Questrial", 1, 66)); // NOI18N
        appName.setForeground(new java.awt.Color(255, 255, 255));
        appName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appName.setText("Skillbridge");
        getContentPane().add(appName, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 330, -1));

        blackMarker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blackMarker.png"))); // NOI18N
        getContentPane().add(blackMarker, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 256, -1, -1));

        bienvenidoTitle.setFont(new java.awt.Font("Questrial", 0, 66)); // NOI18N
        bienvenidoTitle.setForeground(new java.awt.Color(255, 255, 255));
        bienvenidoTitle.setText("Bienvenido");
        getContentPane().add(bienvenidoTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 340, 90));

        loginBtn.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        signupBtn.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        signupBtn.setForeground(new java.awt.Color(255, 255, 255));
        signupBtn.setText("Sign Up");
        getContentPane().add(signupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 90, 30));

        skillbridgeName.setFont(new java.awt.Font("Questrial", 0, 36)); // NOI18N
        skillbridgeName.setForeground(new java.awt.Color(255, 255, 255));
        skillbridgeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        skillbridgeName.setText("SkillBridge");
        getContentPane().add(skillbridgeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 180, 50));

        greenBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greenLargeBoard.png"))); // NOI18N
        getContentPane().add(greenBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 60, 1116, 214));

        whiteBoard.setBackground(new java.awt.Color(204, 204, 204));
        whiteBoard.setForeground(new java.awt.Color(102, 102, 102));
        whiteBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteBoard.png"))); // NOI18N
        getContentPane().add(whiteBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1290, 710));

        bc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bc.png"))); // NOI18N
        getContentPane().add(bc, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 1290, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTxtActionPerformed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void registrarBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarBtnMouseMoved
        registrarBtn.setBackground(new Color(38, 114, 116));

    }//GEN-LAST:event_registrarBtnMouseMoved

    private void registrarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarBtnMouseExited
        registrarBtn.setBackground(new Color(4, 174, 178));

    }//GEN-LAST:event_registrarBtnMouseExited

    private void registrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarBtnMouseClicked
        //Cierra la ventana actual (login)
        // this.dispose();
        //Abre la ventana nueva 
        //login nuevaventana = new login(); 
        //nuevaventana.setVisible(true);
        // Crear el objeto Usuario
        Usuario usuario = new Usuario();

        String id = IDTxt.getText();
        String nombre = nameTxt.getText();
        String apellido = lastnameTxt.getText();
        String correo = emailTxt.getText();
        String contrasena = new String(passTxt.getPassword());
        String repetir = new String(passAgaintxt.getPassword());
        String rol = rolTxt.getSelectedItem().toString();
        String telefono = phoneTxt.getText();

        if (id.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || correo.isEmpty()
                || contrasena.isEmpty() || repetir.isEmpty() || rol.isEmpty() || telefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ Debes completar todos los campos antes de registrar.");
            return;
        }

        if (!contrasena.equals(repetir)) {
            JOptionPane.showMessageDialog(this, "❌ Las contraseñas no coinciden.");
            return;
        }

        // Si el rol es "Monitor/tutor", pedir llave
        if (rol.equals("Monitor/tutor")) {
            String llaveIngresada = JOptionPane.showInputDialog(this, "Ingrese la llave de acceso para monitores/tutores:");
            if (llaveIngresada == null || llaveIngresada.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "❌ No se ingresó ninguna llave. Registro cancelado.");
                return;
            }

            boolean llaveValida = usuario.verificarLlaveAcceso(id, llaveIngresada);
            if (!llaveValida) {
                JOptionPane.showMessageDialog(this, "❌ Llave incorrecta o no registrada.");
                return;
            }
        }

        boolean ok = usuario.registrarUsuarioSQLite(id, nombre, apellido, correo, contrasena, rol, telefono);

        if (ok) {
            JOptionPane.showMessageDialog(this, "✅ Usuario registrado correctamente.\nAhora puedes iniciar sesión.");

            // 🔹 Redirige al login (no abre el perfil aún)
            this.dispose();
            login ventanaLogin = new login();
            ventanaLogin.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "❌ Error al registrar el usuario.");
        }


    }//GEN-LAST:event_registrarBtnMouseClicked

    private void passTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMousePressed
        if (String.valueOf(passTxt.getPassword()).equals("Password")) {
            passTxt.setText("");
        }
    }//GEN-LAST:event_passTxtMousePressed

    private void passAgaintxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passAgaintxtMousePressed
        if (String.valueOf(passAgaintxt.getPassword()).equals("Password")) {
            passAgaintxt.setText("");
        }
    }//GEN-LAST:event_passAgaintxtMousePressed

    private void rolTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDTitle;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JLabel aTitle;
    private javax.swing.JLabel appName;
    private javax.swing.JLabel arrow;
    private javax.swing.JLabel bc;
    private javax.swing.JLabel bienvenidoTitle;
    private javax.swing.JLabel blackMarker;
    private javax.swing.JLabel emailTitle;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel gradHatbig;
    private javax.swing.JLabel gradHatsmall;
    private javax.swing.JLabel greenBoard;
    private javax.swing.JLabel lastnameTitle;
    private javax.swing.JTextField lastnameTxt;
    private javax.swing.JLabel loginBtn;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoWhite;
    private javax.swing.JLabel manGrad;
    private javax.swing.JLabel nameTitle;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel passAgaintitle;
    private javax.swing.JPasswordField passAgaintxt;
    private javax.swing.JLabel passTitle;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JLabel phoneTitle;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JLabel phraseStart;
    private javax.swing.JPanel registrarBtn;
    private javax.swing.JLabel registrarTxt;
    private javax.swing.JLabel rolTitle;
    private javax.swing.JComboBox<String> rolTxt;
    private javax.swing.JLabel signupBtn;
    private javax.swing.JLabel skillbridgeName;
    private javax.swing.JLabel starBig;
    private javax.swing.JLabel starMini;
    private javax.swing.JLabel whiteBoard;
    private javax.swing.JLabel woman1;
    private javax.swing.JLabel woman2;
    // End of variables declaration//GEN-END:variables
}
